// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TankToys.Database;

#nullable disable

namespace TankToys.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240416182755_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TankToys.Models.User", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Address");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Address = "0x0000000000000000000000000000000000000000",
                            Level = 1,
                            ProfileImage = "",
                            Username = "TestUser1"
                        },
                        new
                        {
                            Address = "0x0000000000000000000000000000000000000001",
                            Level = 1,
                            ProfileImage = "",
                            Username = "TestUser2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
